In [1]:
import pandas as pd
import torch
import numpy as np
import torch.nn as nn


In [2]:
data = pd.read_csv("candy-data.csv")
data

competitorname  chocolate  fruity  caramel  peanutyalmondy  \
0                    100 Grand          1       0        1               0   
1                 3 Musketeers          1       0        0               0   
2                     One dime          0       0        0               0   
3                  One quarter          0       0        0               0   
4                    Air Heads          0       1        0               0   
..                         ...        ...     ...      ...             ...   
80                   Twizzlers          0       1        0               0   
81                    Warheads          0       1        0               0   
82        Welch's Fruit Snacks          0       1        0               0   
83  Werther's Original Caramel          0       0        1               0   
84                    Whoppers          1       0        0               0   

    nougat  crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0        0                 1     0    1         0         0.732         0.860   
1        1                 0     0    1         0         0.604         0.511   
2        0                 0     0    0         0         0.011         0.116   
3        0                 0     0    0         0         0.011         0.511   
4        0                 0     0    0         0         0.906         0.511   
..     ...               ...   ...  ...       ...           ...           ...   
80       0                 0     0    0         0         0.220         0.116   
81       0                 0     1    0         0         0.093         0.116   
82       0                 0     0    0         1         0.313         0.313   
83       0                 0     1    0         0         0.186         0.267   
84       0                 1     0    0         1         0.872         0.848   

    winpercent  
0    66.971725  
1    67.602936  
2    32.261086  
3    46.116505  
4    52.341465  
..         ...  
80   45.466282  
81   39.011898  
82   44.375519  
83   41.904308  
84   49.524113  

[85 rows x 13 columns]

In [3]:
X = data.values[: , 1:-1]
X = np.array(X , dtype=np.float32)
X

array([[1.   , 0.   , 1.   , 0.   , 0.   , 1.   , 0.   , 1.   , 0.   ,
        0.732, 0.86 ],
       [1.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 1.   , 0.   ,
        0.604, 0.511],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.011, 0.116],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.011, 0.511],
       [0.   , 1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.906, 0.511],
       [1.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 1.   , 0.   ,
        0.465, 0.767],
       [1.   , 0.   , 1.   , 1.   , 1.   , 0.   , 0.   , 1.   , 0.   ,
        0.604, 0.767],
       [0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   , 1.   ,
        0.313, 0.511],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   ,
        0.906, 0.325],
       [0.   , 1.   , 1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.604, 0.325],
       [1.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 1. 

In [4]:
y = data.values[: , [-1]]
y = np.array(y , dtype=np.float32)
y

array([[66.971725],
       [67.602936],
       [32.261086],
       [46.116505],
       [52.341465],
       [50.347546],
       [56.914547],
       [23.417824],
       [38.010963],
       [34.51768 ],
       [38.975037],
       [36.017628],
       [24.524988],
       [42.272076],
       [39.460556],
       [43.088924],
       [39.185505],
       [46.783348],
       [57.11974 ],
       [34.15896 ],
       [51.41243 ],
       [42.178772],
       [55.375454],
       [62.28448 ],
       [56.4905  ],
       [59.236122],
       [28.12744 ],
       [57.21925 ],
       [76.7686  ],
       [41.389557],
       [39.141056],
       [52.911392],
       [71.46505 ],
       [66.574585],
       [46.411716],
       [55.06407 ],
       [73.099556],
       [60.8007  ],
       [64.35334 ],
       [47.829754],
       [54.52645 ],
       [55.354046],
       [70.73564 ],
       [66.47068 ],
       [22.445341],
       [39.4468  ],
       [46.296597],
       [69.48379 ],
       [37.722336],
       [41.26551 ],


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test , y_train , y_test = train_test_split(X , y ,test_size= 0.2 ,random_state=42)

In [6]:
X_train = torch.tensor(X_train).cuda()
X_test = torch.tensor(X_test).cuda()
y_train = torch.tensor(y_train).cuda()
y_test = torch.tensor(y_test).cuda()

In [7]:




class LinearRegressionModel(torch.nn.Module):
 
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = torch.nn.Linear(11, 6)  # One in and one out
        self.relu = nn.ReLU()
        self.output = torch.nn.Linear(6, 1)
    def forward(self, x):
        y_pred = self.linear(x)
        y_pred = self.relu(y_pred)
        y_pred = self.output(y_pred)
        return y_pred

In [8]:
model =LinearRegressionModel().cuda()
criterion = torch.nn.HuberLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)


In [9]:
global loss_
loss_ = torch.tensor(0 , dtype=torch.float32).cuda()
def is_early_stop(loss):
    global loss_

    if torch.sqrt((loss_ - loss) **2) < 2 :
        return True
    
    else :
        loss_ = loss.clone()

In [10]:




for epoch in range(3000):
 
    # Forward pass: Compute predicted y by passing 
    # x to the model
    pred_y = model(X_train)
 
    # Compute and print loss
    loss = criterion(pred_y, y_train)
    # Zero gradients, perform a backward pass, 
    # and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print('epoch {}, loss {}'.format(epoch, loss.item()))

    
    # Check for early stopping
    # if is_early_stop(loss):
    #     print("Early stopping at epoch {}".format(epoch))
    #     break

epoch 0, loss 49.676937103271484
epoch 1, loss 49.638580322265625
epoch 2, loss 49.60386657714844
epoch 3, loss 49.57107162475586
epoch 4, loss 49.54080581665039
epoch 5, loss 49.511962890625
epoch 6, loss 49.483951568603516
epoch 7, loss 49.45645523071289
epoch 8, loss 49.429141998291016
epoch 9, loss 49.40164566040039
epoch 10, loss 49.373600006103516
epoch 11, loss 49.343868255615234
epoch 12, loss 49.31196212768555
epoch 13, loss 49.278228759765625
epoch 14, loss 49.2423210144043
epoch 15, loss 49.20347213745117
epoch 16, loss 49.15999984741211
epoch 17, loss 49.11309051513672
epoch 18, loss 49.06258010864258
epoch 19, loss 49.00749206542969
epoch 20, loss 48.949127197265625
epoch 21, loss 48.88771438598633
epoch 22, loss 48.823177337646484
epoch 23, loss 48.75541305541992
epoch 24, loss 48.683929443359375
epoch 25, loss 48.60811996459961
epoch 26, loss 48.527687072753906
epoch 27, loss 48.44269561767578
epoch 28, loss 48.353370666503906
epoch 29, loss 48.25959777832031
epoch 30, l

In [11]:
model.eval()

for epoch in range(1):
 
    # Forward pass: Compute predicted y by passing 
    # x to the model
    with torch.no_grad():
        pred_y = model(X_test)
 
    # Compute and print loss
    loss = criterion(pred_y, y_test)
 
    # Zero gradients, perform a backward pass, 
    # and update the weights.
  
    print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 0, loss 9.013262748718262


In [12]:
y_test

tensor([[47.1732],
        [66.9717],
        [67.0376],
        [55.3755],
        [24.5250],
        [44.3755],
        [38.9750],
        [57.1197],
        [52.3415],
        [59.8640],
        [54.5265],
        [69.4838],
        [55.0641],
        [27.3039],
        [35.2908],
        [72.8879],
        [66.5746]], device='cuda:0')

In [13]:
pred_y

tensor([[42.9724],
        [70.3493],
        [42.1981],
        [58.1901],
        [41.1025],
        [42.7026],
        [62.3723],
        [42.8750],
        [44.6436],
        [42.2074],
        [67.7822],
        [69.6911],
        [60.1461],
        [42.1770],
        [38.3819],
        [71.4076],
        [59.6326]], device='cuda:0')

In [14]:
rmse = torch.sqrt(torch.mean(pred_y - y_test ) ** 2)
rmse

tensor(0.2319, device='cuda:0')